Feature/anew/taxi driver trip info
KATJ-HH2/katj pull request #105
Opened 2023-10-17 11:56 UTC by Yoojin-An

# 해결하려는 문제가 무엇인가요?
* 기사님 예상 경로, 요금 조회 기능 추가
* dev branch와 TaxiDriver 엔티티 정의 파일 위치가 다름

# 어떻게 해결했나요?
* trip에서 처리함
* taxidriver/model/TaxiDriver -> taxidriver/model/entity/TaxiDriver로 위치 변경

## Attachment

2023-10-17 16:54 UTC, TonyKim9401 approved these changes
고생하셨습니다~
머지 전에 중간에 아마 확인용으로 작성해두신 pringln(~) 정리 부탁드려요!

2023-10-17 16:54 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/taxidriver/component/TaxiDriverManager.kt
> +    }
경우에 따라 기사님 상태 조회시 ENUM 만 반환하기 보다 택시 기사 객체 자체를 반환해도 좋을것 같아요!

2023-10-17 16:54 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/taxidriver/component/TaxiDriverManager.kt
> +        }
이게..줄곧 생각이 드는게 저도 실수한 부분이지만, RuntimeException을 고려해서 나중에 다시 리팩토링을 해야할 것 같습니다 ㅜ

2023-10-17 16:54 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/trip/component/TripReader.kt
> +    fun findTripInfoByTaxiDriverId(taxiDriverId: Long): List<Any> {
음? List 제네릭을 Any 해두신게 혹시  다건 조회시 결과가 0일수도 있어서 그렇게 해두신 걸까요?

2023-10-17 16:54 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/trip/controller/TripController.kt
> +    fun findTripInfoByTaxiDriverId(@RequestParam taxiDriverId: Long): ResponseEntity<List<Any>> {
여기도 마찬가지구요

2023-10-17 23:22 UTC, Yoojin-An commented on src/main/kotlin/com/hh2/katj/trip/component/TripReader.kt
> +    fun findTripInfoByTaxiDriverId(taxiDriverId: Long): List<Any> {
음.. 요소가 3개인데 자료형이 String, String, Int여서요!

2023-10-17 23:22 UTC, Yoojin-An commented on src/main/kotlin/com/hh2/katj/taxidriver/component/TaxiDriverManager.kt
> +        }
아핫 넵~

2023-10-18 08:36 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/trip/component/TripReader.kt
> +    fun findTripInfoByTaxiDriverId(taxiDriverId: Long): List<Any> {
결과 잘 나오나요??

2023-10-18 17:30 UTC, JangHyeonJun2 requested changes
안녕하세요~! 유진님 
전체적으로 Service로직은 잘 작성하셨네요! 궁금한 부분을 조금 남겼습니다.

또한 Service 로직을 작성하신거에 비해 테스트코드가 조금 더 작성해보면 좋을거같아요~! 
확인부탁드립니다.

2023-10-18 17:30 UTC, JangHyeonJun2 commented on src/main/kotlin/com/hh2/katj/taxidriver/component/TaxiDriverManager.kt
> +        }
여기서 어떤 Exception이 발생하는건가요??
택시드라이버 도메인 로직 같은데, 상태변경할 때 간혹 exception이 발생하나요??

2023-10-18 17:30 UTC, JangHyeonJun2 commented on src/main/kotlin/com/hh2/katj/taxidriver/controller/TaxiDriverController.kt
> +//        val taxiDriver = taxiDriverService.checkValidation(id)
코드 주석은 최대한 삭제부탁드립니다~!

2023-10-18 17:30 UTC, JangHyeonJun2 commented on src/main/kotlin/com/hh2/katj/trip/component/TripReader.kt
> +    fun findTripInfoByTaxiDriverId(taxiDriverId: Long): List<Any> {
타입이 어떤게 나올지 몰라 Any로 두신거같은뎁, 반환할 때 타입이 정해지지않나요?

2023-10-18 17:30 UTC, JangHyeonJun2 commented on src/main/kotlin/com/hh2/katj/taxidriver/service/TaxiDriverService.kt
> +    fun checkValidation(taxiDriverId: Long): TaxiDriver {
CallingService쪽에서 해당 메서드를 호출하던데, 메서드 이름만 봤었을 때는 검증하는줄 알았는데, 아이디를 받고 TaxiDriver의 Enitity를 반환하는거 같아서요! 메서드 이름을 수정하는것도 괜찮을거같아요! 유진님은 어떠세요?

2023-10-18 17:30 UTC, JangHyeonJun2 commented on src/main/kotlin/com/hh2/katj/trip/service/CallingService.kt
> +        println("validatedTaxiDriver")
여기는 logger를 사용하는건 어떠세요? 아니면 지우는것도 괜찮을거같습니다!

2023-10-18 17:30 UTC, JangHyeonJun2 commented on src/test/kotlin/com/hh2/katj/taxidriver/service/TaxiDriverService.kt
> +    fun `택시 저장`(){
테스트코드의 검증부분이 조금 더 추가하면 좋을거같아요~!

2023-10-19 06:31 UTC, Yoojin-An commented on src/main/kotlin/com/hh2/katj/trip/component/TripReader.kt
> +    fun findTripInfoByTaxiDriverId(taxiDriverId: Long): List<Any> {
결과는 잘 나옵니다~ 리스트 안의 요소 타입이 출발지(String), 도착지(String), 요금(Int)로 정해져 있고 이렇게 하나의 리스트가 여러 자료형으로 구성된 경우 리스트의 자료형을 Any로 지정하는 것 같던데 아닌가용?

2023-10-19 06:32 UTC, Yoojin-An commented on src/test/kotlin/com/hh2/katj/taxidriver/service/TaxiDriverService.kt
> +    fun `택시 저장`(){
넵!

2023-10-19 06:32 UTC, Yoojin-An commented on src/main/kotlin/com/hh2/katj/trip/service/CallingService.kt
> +        println("validatedTaxiDriver")
이부분은 지웠습니다ㅎㅎ

2023-10-19 06:35 UTC, Yoojin-An commented on src/main/kotlin/com/hh2/katj/taxidriver/service/TaxiDriverService.kt
> +    fun checkValidation(taxiDriverId: Long): TaxiDriver {
Id가 존재해야 TaxiDriver의 Entity가 반환돼서 Validation 확인의 의미도 있다고 생각했었어요~
그럼 getTaxiDriver 또는 findTaxiDriver 어떤가용??

2023-10-19 06:36 UTC, Yoojin-An commented on src/main/kotlin/com/hh2/katj/taxidriver/controller/TaxiDriverController.kt
> +//        val taxiDriver = taxiDriverService.checkValidation(id)
넵!

2023-10-19 06:38 UTC, Yoojin-An commented on src/main/kotlin/com/hh2/katj/taxidriver/component/TaxiDriverManager.kt
> +    }
기능이 기사님 상태 조회라서 taxi_driver.status만  반환하도록 했는데 택시 기사 객체 자체를 반환하는 경우라면 예외가 발생한 경우일까요??

2023-10-19 07:22 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/taxidriver/component/TaxiDriverManager.kt
> +        }
> 여기서 어떤 Exception이 발생하는건가요?? 택시드라이버 도메인 로직 같은데, 상태변경할 때 간혹 exception이 발생하나요??

아뇨..사실 지금 상황에서 적합한 로직은 아닌것 같습니다

2023-10-19 11:54 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/taxidriver/component/TaxiDriverManager.kt
> +    }
아뇨 상태가 바뀐 정보를 들고있는 택시기사 객체요!

2023-10-19 11:56 UTC, TonyKim9401 commented on src/main/kotlin/com/hh2/katj/trip/component/TripReader.kt
> +    fun findTripInfoByTaxiDriverId(taxiDriverId: Long): List<Any> {
반환값으로 Trip이 나온다고 생각해서 List<Trip>를 하면 될것 같다고 생각했어요 :)

2023-10-20 12:58 UTC, JangHyeonJun2 approved these changes

2023-10-20 12:58 UTC, JangHyeonJun2 commented
Test Code Build 만 통과하면 되겠네요.

2023-10-26 03:18 UTC, anewjean reviewed
Feature/anew/taxi driver trip info PR에 대한 comment 반영

2023-10-26 03:26 UTC, merged